services:
  mongodb:
    container_name: mongodb
    networks:
      - cdp-network
    image: mongo:6.0.13
    volumes:
      - ./ssl:/etc/ssl:ro
    command: [
      "--tlsMode", "requireTLS",
      "--tlsCertificateKeyFile", "etc/ssl/mongodb.pem"
    ]
  service:
    build:
      context: ../..
    container_name: cdp-node-backend-template
    networks:
      - cdp-network
    ports:
      - "8085:8085"
    depends_on:
      - mongodb
    environment:
      PORT: 8085
      MONGO_URI: "mongodb://mongodb:27017/?tls=true"
      TRUSTSTORE_MONGO: ${MONGODB_TEST_CA_PEM}
      LOG_ENABLED: true
      LOG_FORMAT: ecs
      LOG_LEVEL: info
      LOG_REDACT: 'req.headers.authorization,req.headers.cookie,res.headers'
      MONGO_DATABASE: cdp-node-backend-template
      ENABLE_SECURE_CONTEXT: true
      ENABLE_METRICS: true
      TRACING_HEADER: x-cdp-request-id
      ENVIRONMENT: dev
    healthcheck:
      test: curl http://localhost:8085/health
      start_period: 1s
      interval: 2s

networks:
  cdp-network:
    driver: bridge
